name: Deploy NestJS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the Node.js version as per your project requirements

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/new-nestjs
            git fetch origin main  # Fetch the latest changes from the main branch
            git reset --hard origin/main  # Reset local changes to match the main branch
            npm install --production  # Install production dependencies only
            pm2 restart new-nestjs || pm2 start npm --name "new-nestjs" -- start
